set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
set mouse=a
set backupdir=~/.vim/backup
set directory=~/.vim/swap
set hls
set ruler
syntax on
colorscheme distinguished
execute pathogen#infect()
